/*
 * linktype.c
 *
 *  Created on: Jul 20, 2019
 *      Author: mislav
 */

#include "linktype.h"


//Push all the different header link layer types and set them as globals in Lua
void setHeaderLinkTypeValues(lua_State *L) {
	lua_pushnumber(L, 0);
	lua_setfield(L, -2, "LINKTYPE_NULL");
	lua_pushnumber(L, 1);
	lua_setfield(L, -2, "LINKTYPE_ETHERNET");
	lua_pushnumber(L, 3);
	lua_setfield(L, -2, "LINKTYPE_AX25");
	lua_pushnumber(L, 6);
	lua_setfield(L, -2, "LINKTYPE_IEEE802_5");
	lua_pushnumber(L, 7);
	lua_setfield(L, -2, "LINKTYPE_ARCNET_BSD");
	lua_pushnumber(L, 8);
	lua_setfield(L, -2, "LINKTYPE_SLIP");
	lua_pushnumber(L, 9);
	lua_setfield(L, -2, "LINKTYPE_PPP");
	lua_pushnumber(L, 10);
	lua_setfield(L, -2, "LINKTYPE_FDDI");
	lua_pushnumber(L, 50);
	lua_setfield(L, -2, "LINKTYPE_PPP_HDLC");
	lua_pushnumber(L, 51);
	lua_setfield(L, -2, "LINKTYPE_PPP_ETHER");
	lua_pushnumber(L, 100);
	lua_setfield(L, -2, "LINKTYPE_ATM_RFC1483");
	lua_pushnumber(L, 101);
	lua_setfield(L, -2, "LINKTYPE_RAW");
	lua_pushnumber(L, 104);
	lua_setfield(L, -2, "LINKTYPE_C_HDLC");
	lua_pushnumber(L, 105);
	lua_setfield(L, -2, "LINKTYPE_IEEE802_11");
	lua_pushnumber(L, 107);
	lua_setfield(L, -2, "LINKTYPE_FRELAY");
	lua_pushnumber(L, 108);
	lua_setfield(L, -2, "LINKTYPE_LOOP");
	lua_pushnumber(L, 113);
	lua_setfield(L, -2, "LINKTYPE_LINUX_SLL");
	lua_pushnumber(L, 114);
	lua_setfield(L, -2, "LINKTYPE_LTALK");
	lua_pushnumber(L, 117);
	lua_setfield(L, -2, "LINKTYPE_PFLOG");
	lua_pushnumber(L, 119);
	lua_setfield(L, -2, "LINKTYPE_IEEE802_11_PRISM");
	lua_pushnumber(L, 122);
	lua_setfield(L, -2, "LINKTYPE_IP_OVER_FC");
	lua_pushnumber(L, 123);
	lua_setfield(L, -2, "LINKTYPE_SUNATM");
	lua_pushnumber(L, 127);
	lua_setfield(L, -2, "LINKTYPE_IEEE802_11_RADIOTAP");
	lua_pushnumber(L, 129);
	lua_setfield(L, -2, "LINKTYPE_ARCNET_LINUX");
	lua_pushnumber(L, 138);
	lua_setfield(L, -2, "LINKTYPE_APPLE_IP_OVER_IEEE1394");
	lua_pushnumber(L, 139);
	lua_setfield(L, -2, "LINKTYPE_MTP2_WITH_PHDR");
	lua_pushnumber(L, 140);
	lua_setfield(L, -2, "LINKTYPE_MTP2");
	lua_pushnumber(L, 141);
	lua_setfield(L, -2, "LINKTYPE_MTP3");
	lua_pushnumber(L, 142);
	lua_setfield(L, -2, "LINKTYPE_SCCP");
	lua_pushnumber(L, 143);
	lua_setfield(L, -2, "LINKTYPE_DOCSIS");
	lua_pushnumber(L, 144);
	lua_setfield(L, -2, "LINKTYPE_LINUX_IRDA");
	lua_pushnumber(L, 147);
	lua_setfield(L, -2, "LINKTYPE_USER0");
	lua_pushnumber(L, 148);
	lua_setfield(L, -2, "LINKTYPE_USER1");
	lua_pushnumber(L, 149);
	lua_setfield(L, -2, "LINKTYPE_USER2");
	lua_pushnumber(L, 150);
	lua_setfield(L, -2, "LINKTYPE_USER3");
	lua_pushnumber(L, 151);
	lua_setfield(L, -2, "LINKTYPE_USER4");
	lua_pushnumber(L, 152);
	lua_setfield(L, -2, "LINKTYPE_USER5");
	lua_pushnumber(L, 153);
	lua_setfield(L, -2, "LINKTYPE_USER6");
	lua_pushnumber(L, 154);
	lua_setfield(L, -2, "LINKTYPE_USER7");
	lua_pushnumber(L, 155);
	lua_setfield(L, -2, "LINKTYPE_USER8");
	lua_pushnumber(L, 156);
	lua_setfield(L, -2, "LINKTYPE_USER9");
	lua_pushnumber(L, 157);
	lua_setfield(L, -2, "LINKTYPE_USER10");
	lua_pushnumber(L, 158);
	lua_setfield(L, -2, "LINKTYPE_USER11");
	lua_pushnumber(L, 159);
	lua_setfield(L, -2, "LINKTYPE_USER12");
	lua_pushnumber(L, 160);
	lua_setfield(L, -2, "LINKTYPE_USER13");
	lua_pushnumber(L, 161);
	lua_setfield(L, -2, "LINKTYPE_USER14");
	lua_pushnumber(L, 162);
	lua_setfield(L, -2, "LINKTYPE_USER15");
	lua_pushnumber(L, 163);
	lua_setfield(L, -2, "LINKTYPE_IEEE802_11_AVS");
	lua_pushnumber(L, 165);
	lua_setfield(L, -2, "LINKTYPE_BACNET_MS_TP");
	lua_pushnumber(L, 166);
	lua_setfield(L, -2, "LINKTYPE_PPP_PPPD");
	lua_pushnumber(L, 169);
	lua_setfield(L, -2, "LINKTYPE_GPRS_LLC");
	lua_pushnumber(L, 170);
	lua_setfield(L, -2, "LINKTYPE_GPF_T");
	lua_pushnumber(L, 171);
	lua_setfield(L, -2, "LINKTYPE_GPF_F");
	lua_pushnumber(L, 177);
	lua_setfield(L, -2, "LINKTYPE_LINUX_LAPD");
	lua_pushnumber(L, 182);
	lua_setfield(L, -2, "LINKTYPE_MFR");
	lua_pushnumber(L, 187);
	lua_setfield(L, -2, "LINKTYPE_BLUETOOTH_HCI_H4");
	lua_pushnumber(L, 189);
	lua_setfield(L, -2, "LINKTYPE_USB_LINUX");
	lua_pushnumber(L, 192);
	lua_setfield(L, -2, "LINKTYPE_PPI");
	lua_pushnumber(L, 195);
	lua_setfield(L, -2, "LINKTYPE_IEEE802_15_4_WITHFCS");
	lua_pushnumber(L, 196);
	lua_setfield(L, -2, "LINKTYPE_SITA");
	lua_pushnumber(L, 197);
	lua_setfield(L, -2, "LINKTYPE_ERF");
	lua_pushnumber(L, 201);
	lua_setfield(L, -2, "LINKTYPE_BLUETOOTH_HCI_H4_WITH_PHDR");
	lua_pushnumber(L, 202);
	lua_setfield(L, -2, "LINKTYPE_AX25_KISS");
	lua_pushnumber(L, 203);
	lua_setfield(L, -2, "LINKTYPE_LAPD");
	lua_pushnumber(L, 204);
	lua_setfield(L, -2, "LINKTYPE_PPP_WITH_DIR");
	lua_pushnumber(L, 205);
	lua_setfield(L, -2, "LINKTYPE_C_HDLC_WITH_DIR");
	lua_pushnumber(L, 206);
	lua_setfield(L, -2, "LINKTYPE_FRELAY_WITH_DIR");
	lua_pushnumber(L, 207);
	lua_setfield(L, -2, "LINKTYPE_LAPB_WITH_DIR");
	lua_pushnumber(L, 209);
	lua_setfield(L, -2, "LINKTYPE_IPMB_LINUX");
	lua_pushnumber(L, 215);
	lua_setfield(L, -2, "LINKTYPE_IEEE802_15_4_NONASK_PHY");
	lua_pushnumber(L, 220);
	lua_setfield(L, -2, "LINKTYPE_USB_LINUX_MMAPPED");
	lua_pushnumber(L, 224);
	lua_setfield(L, -2, "LINKTYPE_FC_2");
	lua_pushnumber(L, 225);
	lua_setfield(L, -2, "LINKTYPE_FC_2_WITH_FRAME_DELIMS");
	lua_pushnumber(L, 226);
	lua_setfield(L, -2, "LINKTYPE_IPNET");
	lua_pushnumber(L, 227);
	lua_setfield(L, -2, "LINKTYPE_CAN_SOCKETCAN");
	lua_pushnumber(L, 228);
	lua_setfield(L, -2, "LINKTYPE_IPV4");
	lua_pushnumber(L, 229);
	lua_setfield(L, -2, "LINKTYPE_IPV6");
	lua_pushnumber(L, 230);
	lua_setfield(L, -2, "LINKTYPE_IEEE802_15_4_NOFCS");
	lua_pushnumber(L, 231);
	lua_setfield(L, -2, "LINKTYPE_DBUS");
	lua_pushnumber(L, 235);
	lua_setfield(L, -2, "LINKTYPE_DVB_CI");
	lua_pushnumber(L, 236);
	lua_setfield(L, -2, "LINKTYPE_MUX27010");
	lua_pushnumber(L, 237);
	lua_setfield(L, -2, "LINKTYPE_STANAG_5066_D_PDU");
	lua_pushnumber(L, 239);
	lua_setfield(L, -2, "LINKTYPE_NFLOG");
	lua_pushnumber(L, 240);
	lua_setfield(L, -2, "LINKTYPE_NETANALYZER");
	lua_pushnumber(L, 241);
	lua_setfield(L, -2, "LINKTYPE_NETANALYZER_TRANSPARENT");
	lua_pushnumber(L, 242);
	lua_setfield(L, -2, "LINKTYPE_IPOIB");
	lua_pushnumber(L, 243);
	lua_setfield(L, -2, "LINKTYPE_MPEG_2_TS");
	lua_pushnumber(L, 244);
	lua_setfield(L, -2, "LINKTYPE_NG40");
	lua_pushnumber(L, 245);
	lua_setfield(L, -2, "LINKTYPE_NFC_LLCP");
	lua_pushnumber(L, 247);
	lua_setfield(L, -2, "LINKTYPE_INFINIBAND");
	lua_pushnumber(L, 248);
	lua_setfield(L, -2, "LINKTYPE_SCTP");
	lua_pushnumber(L, 249);
	lua_setfield(L, -2, "LINKTYPE_USBPCAP");
	lua_pushnumber(L, 250);
	lua_setfield(L, -2, "LINKTYPE_RTAC_SERIAL");
	lua_pushnumber(L, 251);
	lua_setfield(L, -2, "LINKTYPE_BLUETOOTH_LE_LL");
	lua_pushnumber(L, 253);
	lua_setfield(L, -2, "LINKTYPE_NETLINK");
	lua_pushnumber(L, 254);
	lua_setfield(L, -2, "LINKTYPE_BLUETOOTH_LINUX_MONITOR");
	lua_pushnumber(L, 255);
	lua_setfield(L, -2, "LINKTYPE_BLUETOOTH_BREDR_BB");
	lua_pushnumber(L, 256);
	lua_setfield(L, -2, "LINKTYPE_BLUETOOTH_LE_LL_WITH_PHDR");
	lua_pushnumber(L, 257);
	lua_setfield(L, -2, "LINKTYPE_PROFIBUS_DL");
	lua_pushnumber(L, 258);
	lua_setfield(L, -2, "LINKTYPE_PKTAP");
	lua_pushnumber(L, 259);
	lua_setfield(L, -2, "LINKTYPE_EPON");
	lua_pushnumber(L, 260);
	lua_setfield(L, -2, "LINKTYPE_IPMI_HPM_2");
	lua_pushnumber(L, 261);
	lua_setfield(L, -2, "LINKTYPE_ZWAVE_R1_R2");
	lua_pushnumber(L, 262);
	lua_setfield(L, -2, "LINKTYPE_ZWAVE_R3");
	lua_pushnumber(L, 263);
	lua_setfield(L, -2, "LINKTYPE_WATTSTOPPER_DLM");
	lua_pushnumber(L, 264);
	lua_setfield(L, -2, "LINKTYPE_ISO_14443");
	lua_pushnumber(L, 265);
	lua_setfield(L, -2, "LINKTYPE_RDS");
	lua_pushnumber(L, 266);
	lua_setfield(L, -2, "LINKTYPE_USB_DARWIN");
	lua_pushnumber(L, 268);
	lua_setfield(L, -2, "LINKTYPE_SDLC");
	lua_pushnumber(L, 270);
	lua_setfield(L, -2, "LINKTYPE_LORATAP");
	lua_pushnumber(L, 271);
	lua_setfield(L, -2, "LINKTYPE_VSOCK");
	lua_pushnumber(L, 272);
	lua_setfield(L, -2, "LINKTYPE_NORDIC_BLE");
	lua_pushnumber(L, 273);
	lua_setfield(L, -2, "LINKTYPE_DOCSIS31_XRA31");
	lua_pushnumber(L, 274);
	lua_setfield(L, -2, "LINKTYPE_ETHERNET_MPACKET");
	lua_pushnumber(L, 275);
	lua_setfield(L, -2, "LINKTYPE_DISPLAYPORT_AUX");
	lua_pushnumber(L, 276);
	lua_setfield(L, -2, "LINKTYPE_LINUX_SLL2");
	lua_pushnumber(L, 278);
	lua_setfield(L, -2, "LINKTYPE_OPENVIZSLA");
	lua_pushnumber(L, 279);
	lua_setfield(L, -2, "LINKTYPE_EBHSCR");
	lua_pushnumber(L, 280);
	lua_setfield(L, -2, "LINKTYPE_VPP_DISPATCH");
	lua_pushnumber(L, 281);
	lua_setfield(L, -2, "LINKTYPE_DSA_TAG_BRCM");
	lua_pushnumber(L, 282);
	lua_setfield(L, -2, "LINKTYPE_DSA_TAG_BRCM_PREPEND");
	lua_pushnumber(L, 283);
	lua_setfield(L, -2, "LINKTYPE_IEEE802_15_4_TAP");
	lua_pushnumber(L, 284);
	lua_setfield(L, -2, "LINKTYPE_DSA_TAG_DSA");
	lua_pushnumber(L, 285);
	lua_setfield(L, -2, "LINKTYPE_DSA_TAG_EDSA");
	lua_pushnumber(L, 286);
	lua_setfield(L, -2, "LINKTYPE_ELEE");
	lua_pushnumber(L, 287);
	lua_setfield(L, -2, "LINKTYPE_Z_WAVE_SERIAL");
	lua_pushnumber(L, 288);
	lua_setfield(L, -2, "LINKTYPE_USB_2_0");
}
